import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import SearchProvider from "./contexts/search/SearchProvider";
import NavProvider from "./contexts/nav/NavProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-[#1e1e1f] scrollbar-hide"}>
        <NavProvider>
          <SearchProvider>
            {children}
            <Navbar />
          </SearchProvider>
        </NavProvider>
      </body>
    </html>
  );
}
